sudo: false
language: perl
addons:
  apt:
    packages:
      - build-essential
      - ikiwiki
      - libtext-multimarkdown-perl
      - libimage-magick-perl
install:
  - openssl aes-256-cbc -K $encrypted_97fba1a3df90_key -iv $encrypted_97fba1a3df90_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global push.default simple
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  - COMMIT_MESSAGE="Publishing site on `date "+%Y-%m-%d %H:%M:%S"` from
    `git log -n 1 --format='commit %h - %s'`"
  - GH_PAGES_REPO="git@github.com:${TRAVIS_REPO_SLUG}.git"
  - GH_PAGES_BRANCH="gh-pages"
script:
  #- set -e
  - ikiwiki --rebuild . _site
  - git clone --bare -b "$GH_PAGES_BRANCH" "$GH_PAGES_REPO" _site/.git
  - cd _site
  - git config core.bare false
  - git add -f .
  - 'git commit -m "${COMMIT_MESSAGE}"'
  - git push -f "$GH_PAGES_REPO" "$GH_PAGES_BRANCH":"$GH_PAGES_BRANCH"

branches:
  only:
    - master
